# $Id: Makefile,v 1.3 2001/09/09 03:23:18 almightyjustin Exp $

XCFLAGS =
OBJS	=
DFILES	= Makefile Rules.djgpp Rules.go32 Rules.mingw32 Rules.xmingw32
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../Rules

