# $Id: Makefile,v 1.3 2001/08/23 15:36:56 cmatsuoka Exp $

XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
DDIRS	= msdos win32 unix macos amiga
XDFILES =
LIB	=

all:
	(cd $(FILEIO_DRIVER); $(MAKE) all)

include ../../Rules

