# $Id: Makefile,v 1.3 2001/09/13 17:24:03 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= sdl.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules

