# $Id: Makefile,v 1.2 2001/08/02 16:12:40 cmatsuoka Exp $

XCFLAGS =
OBJS	=
DFILES	= Makefile config.guess config.sub install-sh cflow2dot.pl
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../Rules

