# $Id: Makefile,v 1.5 2001/08/23 15:36:56 cmatsuoka Exp $

XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
DDIRS	= oss sdl dummy alsa bsd solaris sgi win32 freebsd qnx dart amiga
XDFILES =
LIB	=

all:
	(cd $(SOUND_DRIVER); $(MAKE) all)

include ../../Rules

